### ISSUE TITLE
Numbered lists break codeblocks.

### ISSUE THREAD

**Issue by ElijahCaine** [mythmon/wok#131]
When a code-block is embedded in a numbered list 
1. Thing
```
   $baz
```
2. Thing too
```
    foo
    $ bar
```
Renders as
1. Thing 
    $bax
2. Thing too
    foo$bar

With a fresh installation of wok through pip.

**Comment by mythmon** [comment]
This is an issue with Markdown, not wok. You'll notice GitHub does a similiar thing.

The correct way to do this would be

1. Foo

   ```
   $foo
   ```
2. Bar

   ```
   $bar
   ``` 

That is, 


    1. Foo
    
       ```
       $foo
       ```
    2. Bar
    
       ```
       $bar
       ```
