### ISSUE TITLE
Installing from git clone: can't find contrib.hooks

### ISSUE THREAD

**Issue by xenovacivus** [mythmon/wok#90]
Following the instructions for installing from github and running "wok" in the docs directory gives the following error message:

<code>ImportError: No module named contrib.hooks</code>

Modifying line 178 in engine.py and recompiling appears to fix the issue.
<code># sys.path.append('hooks')
sys.path.append('contrib')</code>

I'm running Ubuntu 11.10 and Python 2.7.

**Comment by dskecse** [comment]
@gchriz, that worked. @mythmon, do you mind resolving the issue like that?
